# Generated by Django 2.2.1 on 2019-06-10 06:35

import backend.api.models
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[backend.api.models.no_unsafe])),
                ('url', models.CharField(max_length=100, validators=[backend.api.models.no_unsafe])),
                ('image', models.ImageField(null=True, upload_to=backend.api.models.Uuid4Path())),
                ('type', models.IntegerField(choices=[(1, 'member'), (2, 'other')])),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[backend.api.models.no_unsafe])),
                ('content', markdownx.models.MarkdownxField()),
                ('header', models.ImageField(blank=True, null=True, upload_to=backend.api.models.Uuid4Path())),
                ('featured', models.ImageField(blank=True, null=True, upload_to=backend.api.models.Uuid4Path())),
                ('slider', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='EventParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, validators=[backend.api.models.no_unsafe])),
                ('entities', models.ManyToManyField(to='api.Entity')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post')),
            ],
            options={
                'verbose_name_plural': 'Events participants',
            },
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=100, null=True, validators=[backend.api.models.no_unsafe])),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Post')),
            ],
            options={
                'verbose_name_plural': 'Events details',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[backend.api.models.no_unsafe])),
                ('file', models.FileField(upload_to=backend.api.models.Uuid4Path())),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post')),
            ],
        ),
    ]
