# Generated by Django 2.2.1 on 2019-06-16 18:49

import backend.api.utils.uuid4path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190616_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to=backend.api.utils.uuid4path.Uuid4Path()),
        ),
    ]
