# Generated by Django 2.2.1 on 2021-07-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190616_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
    ]
