version: "3"
services:
  proxy:
    build:
      context: ./proxy
    restart: always
    volumes:
      - static_volume:/usr/local/src/app/static
      - media_volume:/usr/local/src/app/media
    ports:
      - 1300:80
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    ports:
      - 8000:8000
    depends_on:
      - db
      - proxy
    volumes:
      - static_volume:/usr/local/src/app/static
      - media_volume:/usr/local/src/app/media
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  static_volume:
  media_volume:
