version: "3"
services:
  app:
    build:
      context: .
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    environment:
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - $PWD:/code
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
